spring:
  application:
    name: 01-rag-fundamentals

  ai:
    openai:
      base-url: https://chat.abc.com/api
      api-key: ${OPENAI_API_KEY}
      chat:
        model: bedrock-claude-v4.5_Sonnet
      embedding:
        model: text-embedding-3-large
